name: learning GitHub Actions
on: push
jobs:
  run-code-checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.1
      - name: Set up Go
        uses: actions/setup-go@v5.0.0
        with:
          go-version: 1.21.3
      - name: Set up Go mod
        run: |
          go mod init github.com/abalbastrem/fizzbuzz_actions
          go mod tidy
      - name: Run fmt
        run: go fmt ./...
      - name: Run vet
        run: go vet ./...
      - name: Run tests
        run: go test